/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.4 at Wed Dec 02 15:53:10 2015. */

#ifndef PB_MESSAGEPROTO_PB_H_INCLUDED
#define PB_MESSAGEPROTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _Control {
    uint32_t steering;
    uint32_t speed;
    uint32_t lights;
    uint32_t gyroTrigger;
} Control;

typedef struct _Sensors {
    uint32_t usFront;
    uint32_t usRear;
    uint32_t irFrontRight;
    uint32_t irRearRight;
    uint32_t irBackLeft;
    uint32_t irBackRight;
    uint32_t GyroHeading;
    uint32_t wheelRearLeft;
    uint32_t wheelRearRight;
    uint32_t buttonState;
    uint32_t lightReading;
} Sensors;

/* Default values for struct fields */

/* Initializer values for message structs */
#define Sensors_init_default                     {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Control_init_default                     {0, 0, 0, 0}
#define Sensors_init_zero                        {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define Control_init_zero                        {0, 0, 0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define Control_steering_tag                     1
#define Control_speed_tag                        2
#define Control_lights_tag                       3
#define Control_gyroTrigger_tag                  4
#define Sensors_usFront_tag                      1
#define Sensors_usRear_tag                       2
#define Sensors_irFrontRight_tag                 3
#define Sensors_irRearRight_tag                  4
#define Sensors_irBackLeft_tag                   5
#define Sensors_irBackRight_tag                  6
#define Sensors_GyroHeading_tag                  7
#define Sensors_wheelRearLeft_tag                8
#define Sensors_wheelRearRight_tag               9
#define Sensors_buttonState_tag                  10
#define Sensors_lightReading_tag                 11

/* Struct field encoding specification for nanopb */
extern const pb_field_t Sensors_fields[12];
extern const pb_field_t Control_fields[5];

/* Maximum encoded size of messages (where known) */
#define Sensors_size                             66
#define Control_size                             24

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MESSAGEPROTO_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
