/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.4 at Wed Dec 02 15:53:10 2015. */

#include "messageproto.pb.h"

#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t Sensors_fields[12] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Sensors, usFront, usFront, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, usRear, usFront, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, irFrontRight, usRear, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, irRearRight, irFrontRight, 0),
    PB_FIELD(  5, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, irBackLeft, irRearRight, 0),
    PB_FIELD(  6, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, irBackRight, irBackLeft, 0),
    PB_FIELD(  7, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, GyroHeading, irBackRight, 0),
    PB_FIELD(  8, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, wheelRearLeft, GyroHeading, 0),
    PB_FIELD(  9, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, wheelRearRight, wheelRearLeft, 0),
    PB_FIELD( 10, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, buttonState, wheelRearRight, 0),
    PB_FIELD( 11, UINT32  , REQUIRED, STATIC  , OTHER, Sensors, lightReading, buttonState, 0),
    PB_LAST_FIELD
};

const pb_field_t Control_fields[5] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, Control, steering, steering, 0),
    PB_FIELD(  2, UINT32  , REQUIRED, STATIC  , OTHER, Control, speed, steering, 0),
    PB_FIELD(  3, UINT32  , REQUIRED, STATIC  , OTHER, Control, lights, speed, 0),
    PB_FIELD(  4, UINT32  , REQUIRED, STATIC  , OTHER, Control, gyroTrigger, lights, 0),
    PB_LAST_FIELD
};


